### ISSUE TITLE
悲剧，跳几下就自杀。。

### ISSUE THREAD

**Issue by nshen** [Shu-Ji/wechat_micro_jump_game_hero#10]
悲剧，跳几下就自杀。。

**Comment by Shu-Ji** [comment]
按照 [说明](https://github.com/Shu-Ji/wechat_micro_jump_game_hero#%E8%B0%83%E8%AF%95%E8%AF%B4%E6%98%8E) 调节参数。

**Comment by nshen** [comment]
![3 png debug](https://user-images.githubusercontent.com/181506/34508022-889f8552-f076-11e7-97ef-1cddfffacc63.png)

3q ，是我的悬浮球作怪，关掉就好了，可加到注意事项中。

另外粉色好像确实不行

**Comment by nshen** [comment]
![98 png debug](https://user-images.githubusercontent.com/181506/34508351-300740d0-f079-11e7-8370-2f56d2bc0359.png)

最高纪录死在这里，粉色背景

**Comment by Shu-Ji** [comment]
是的，亮色系背景效果会差一些，研究了一下，发现hsv对于这里粉色不太适用，这里粉色的h值变化太大，并不是标准的，之前还可以，看了微信源码，更新了背景的渐变方式。
后期考虑使用垂直投影图吧。
