### ISSUE TITLE
跳了几下获取不到位置了

### ISSUE THREAD

**Issue by knoxhy** [Shu-Ji/wechat_micro_jump_game_hero#11]
之前hero pos有坐标，跳几下后坐标变空报错了，怎么回事，小米机
  
![qq 20180103193331](https://user-images.githubusercontent.com/14087371/34519964-9cb10c00-f0c1-11e7-8958-694ed3a3e152.png)

**Comment by Shu-Ji** [comment]
查看/tmp/wechat_micro_jump_game_screenshot/9.png.debug.png
或者，修改 debug 为 True 以及 fn 为 9.png 运行
