### ISSUE TITLE
背景变黑之后程序无法正确判断距离

### ISSUE THREAD

**Issue by rayshaw001** [Shu-Ji/wechat_micro_jump_game_hero#12]
[example picture](https://github.com/rayshaw001/wechat_micro_jump_game_hero/blob/master/issue/issue.png)

**Comment by Shu-Ji** [comment]
debug 参数开启之后，erase_background 方法中会限定擦除背景的高度，你的图片中全黑了，是改了哪里代码呢？

**Comment by rayshaw001** [comment]
图片中背景全黑是游戏中有概率自然出现的，不是修改代码导致的。

**Comment by Shu-Ji** [comment]
微信出现了黑色背景？
还是debug模式下呢？
debug模式下，是有控制的，不会出现全屏为黑的情况。

**Comment by rayshaw001** [comment]
我这边背景全黑目前出现过2次，不确定是不是debug导致的。

**Comment by Shu-Ji** [comment]
代码 [L89](https://github.com/Shu-Ji/wechat_micro_jump_game_hero/blob/master/main.py#L89) 中指定了不会全屏哦。再调试调试看看。

**Comment by rayshaw001** [comment]
我设置的debug=False,[my running code](https://github.com/rayshaw001/wechat_micro_jump_game_hero/blob/8d06b5dd09a898d648956dafd8edaa4a17049efa/main.py#L180)

**Comment by Shu-Ji** [comment]
已经优化了一个版本，之前基于背景的方案可以不用了
