### ISSUE TITLE
iOS如何使用？只能在Android上运行麽

### ISSUE THREAD

**Issue by MrXCQ** [Shu-Ji/wechat_micro_jump_game_hero#14]

**Comment by Shu-Ji** [comment]
是的，iOS无法使用，https://github.com/Shu-Ji/wechat_micro_jump_game_hero/issues/2

**Comment by MrXCQ** [comment]
好吧，平台限制吧？谢谢大神解答了

**Comment by Shu-Ji** [comment]
代码基本通用，但是开发环境需要自己去折腾，没这个精力折腾了
