### ISSUE TITLE
红米3跳不成功

### ISSUE THREAD

**Issue by wuxue0427** [Shu-Ji/wechat_micro_jump_game_hero#15]
模拟点击已打开，截图可以正常保存，从截图来看位置计算也是正确的，但是每次跳都是跳不到第一块上边。设置debug的时候，弹出两个截图，第一个正常，第二个中间位置全白，不知道是什么原因？

**Comment by wuxue0427** [comment]
Traceback (most recent call last):
  File "E:\MyProject\Python\wechat_micro_jump_game_hero-master\main.py", line 198, in <module>
    otsu = Otsu(fp, debug=debug)
  File "E:\MyProject\Python\wechat_micro_jump_game_hero-master\main.py", line 42, in __init__
    is_hero_on_left = self.hero_pos[0] < self. w / 2
IndexError: list index out of range
这是报错信息

**Comment by wuxue0427** [comment]
![image](https://user-images.githubusercontent.com/22740020/34562062-b472e7ac-f187-11e7-8395-28e53145a794.png)

**Comment by Shu-Ji** [comment]
图片挂了，目前 main.py 对于亮色背景（黄色、粉色）不太适用，可以使用 main_cv.py 的版本

**Comment by wuxue0427** [comment]
这个需要哪些库？

**Comment by wuxue0427** [comment]
用main_cv.py还是跳不成功

**Comment by Shu-Ji** [comment]
看起来图像识别没有问题，那应该是分辨率的问题了，调节一下 main.py 中那个 1.5，如果没跳上去，就调大一些，如果跳超过了，就调小一些
