### ISSUE TITLE
cmd异常

### ISSUE THREAD

**Issue by javakam** [Shu-Ji/wechat_micro_jump_game_hero#16]
p install pillow
Collecting pillowpip
  Could not find a version that satisfies the requirement pillowpip (from versions: )
No matching distribution found for pillowpip

**Comment by Shu-Ji** [comment]
看起来是库名输入错误？

```shell
pip install pillow
```

**Comment by javakam** [comment]
还是不行。。
C:\Users\Administrator\Desktop\wechat_micro_jump_game_hero>pip install pillow
Requirement already satisfied: pillow in d:\fastwork\python27\lib\site-packages
main.py可以用，但是跳了几次最高就到58

**Comment by Shu-Ji** [comment]
这是说已经安装成功了。
调整参数，尤其是那个 1.5 参数。
建议使用 main_cv.py 版本

**Comment by javakam** [comment]
main_cv.py也不行啊，跑了三次，最高才20.。。

**Comment by Shu-Ji** [comment]
调节参数，打开 debug ，根据图片远近调节参数
