### ISSUE TITLE
被微信封了吗？

### ISSUE THREAD

**Issue by diaodiao088** [Shu-Ji/wechat_micro_jump_game_hero#17]
跳了 900 多分，好友的排名却并没有更新，是被微信识别到了吗？ 求解...........................

**Comment by Shu-Ji** [comment]
@diaodiao088 应该是被封了，可以查看分析源码时候发现的：https://github.com/Shu-Ji/wechat_micro_jump_game_hero/blob/master/docs/README.md 相关反作弊措施，如果当前点击时间与上次成功跳跃时间差小于 800 毫秒，那么可能会被判断为作弊：

```javascript
// 其中以下不知是否为防作弊代码：
// 两次时间大于 800 毫秒，那么可能导致，判断为“慢”，有可能是在作弊
t.quick = Date.now() - t.lastSucceedTime < 800 || !1
t.quickArr.push(t.quick)
// 发送给服务器
t.gameSocket.sendCommand()
```
