### ISSUE TITLE
执行python android_jump.py 时报错，麻烦大神看一下

### ISSUE THREAD

**Issue by MarsYun** [Shu-Ji/wechat_micro_jump_game_hero#18]
执行python android_jump.py 时报错，麻烦大神看一下

**Comment by MarsYun** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>d:

D:\>cd D:\wechat_micro_jump_game_hero-master

D:\wechat_micro_jump_game_hero-master>python android_jump.py 

'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/tmp/wechat_micro_jump_game_screenshot\0.png
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
Traceback (most recent call last):
  File "android_jump.py 

", line 39, in <module>
    otsu = Otsu(fp, debug, 1.5)
  File "D:\wechat_micro_jump_game_hero-master\libjump.py 

", line 39, in __init__
    self.h, self.w ,_ = self.im 

.shape
AttributeError: 'NoneType' object has no attribute 'shape'
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/tmp/wechat_micro_jump_game_screenshot\1.png
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
Traceback (most recent call last):
  File "android_jump.py 

", line 39, in <module>
    otsu = Otsu(fp, debug, 1.5)
  File "D:\wechat_micro_jump_game_hero-master\libjump.py 

", line 39, in __init__
    self.h, self.w ,_ = self.im 

.shape
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "android_jump.py 

", line 62, in <module>
    time.sleep(2)
KeyboardInterrupt

D:\wechat_micro_jump_game_hero-master>

**Comment by MarsYun** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>d:

D:\>cd D:\wechat_micro_jump_game_hero-master

D:\wechat_micro_jump_game_hero-master>python android_jump.py 

'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/tmp/wechat_micro_jump_game_screenshot\0.png
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
Traceback (most recent call last):
  File "android_jump.py 

", line 39, in <module>
    otsu = Otsu(fp, debug, 1.5)
  File "D:\wechat_micro_jump_game_hero-master\libjump.py 

", line 39, in __init__
    self.h, self.w ,_ = self.im 

.shape
AttributeError: 'NoneType' object has no attribute 'shape'
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
/tmp/wechat_micro_jump_game_screenshot\1.png
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
Traceback (most recent call last):
  File "android_jump.py 

", line 39, in <module>
    otsu = Otsu(fp, debug, 1.5)
  File "D:\wechat_micro_jump_game_hero-master\libjump.py 

", line 39, in __init__
    self.h, self.w ,_ = self.im 

.shape
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "android_jump.py 

", line 62, in <module>
    time.sleep(2)
KeyboardInterrupt

D:\wechat_micro_jump_game_hero-master>

**Comment by Shu-Ji** [comment]
先安装 adb 工具，并添加到环境变量。
