### ISSUE TITLE
iphone 怎么用呢？

### ISSUE THREAD

**Issue by yalishizhude** [Shu-Ji/wechat_micro_jump_game_hero#2]

**Comment by Shu-Ji** [comment]
1 越狱手机将python修改为lua使用按键精灵直接在iPhone运行（不要轻易升级iPhone，新版11.2.x不能越狱）
2 libimobiledevice 截图
3 将iPhone投影到电脑，截电脑的图

**Comment by Shu-Ji** [comment]
@yalishizhude 不好意思，我没有这方面的经验。

**Comment by Shu-Ji** [comment]
安装一个安卓模拟器吧，省得折腾 iOS 的环境。
