### ISSUE TITLE
跳动两百多就掉下去了

### ISSUE THREAD

**Issue by iceuncle** [Shu-Ji/wechat_micro_jump_game_hero#4]

**Comment by Shu-Ji** [comment]
可能是不同手机屏幕分辨率导致的，不知道手机的色彩会否有影响，请参考 [《注意事项》](https://github.com/Shu-Ji/wechat_micro_jump_game_hero#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) 中的说明，手动调节参数。

**Comment by UniqHu** [comment]
小米4  5步到10步,就挂了, 每次都跳远了一丢丢.

**Comment by Shu-Ji** [comment]
@UniqHu 调节1.5那个参数，改小一点，如1.4,1.3
