### ISSUE TITLE
小米6不会跳

### ISSUE THREAD

**Issue by Hsuer** [Shu-Ji/wechat_micro_jump_game_hero#8]
位置信息似乎都是正确的，但是不跳

**Comment by Shu-Ji** [comment]
请确保 adb 截图成功，并成功拉取到相应目录。看报错信息。

**Comment by Hsuer** [comment]
截图成功，我在tmp下可以看到s.png的更新。。。可是不跳，也没报错，目前定位是adb shell input swipe不起作用

**Comment by Hsuer** [comment]
呃。。解决了。需要将小米的USB调试（安全模式）给打开，才能允许模拟点击， Good work
