### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wwjjerry** [Shu-Ji/wechat_micro_jump_game_hero#9]
Windows可以用吗，还有就是那个命令是用什么软件执行的，谢谢！

**Comment by Shu-Ji** [comment]
可以使用，什么命令，需要安装 adb。

**Comment by wwjjerry** [comment]
$ mkvirtualenv wechat_micro_jump_game_hero
$ cdvitualenv
$ git clone ...
$ cd wechat_micro_jump_game_hero
$ echo `pwd` > ../.project
$ pip install pipenv
$ pipenv install
就是像这些命令是在哪里写，谢啦

**Comment by Shu-Ji** [comment]
windows 在 cmd 里面写。
上面的一般对于  linux 比较方便，windows 直接在安装好 python 后，添加环境变量，
在 cmd 中执行

pip install pillow

然后在 cmd 中，运行即可：

python main.py

**Comment by wwjjerry** [comment]
谢啦，我再试试，非常感谢

**Comment by wwjjerry** [comment]
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
c:/wechat_micro_jump_game_screenshot\17.png
Traceback (most recent call last):
  File "main.py", line 198, in <module>
    otsu = Otsu(fp, debug=debug)
  File "main.py", line 33, in __init__
    self.im = Image.open(path)
  File "E:\python\lib\site-packages\PIL\Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'c:/wechat_micro_jump_game_screenshot\\17.png'
这是什么问题

**Comment by Shu-Ji** [comment]
电脑安装 adb

**Comment by wwjjerry** [comment]
adb version
Android Debug Bridge version 1.0.31
安装了，之前运行adb devices 都没有问题，运行 python main.py

**Comment by wwjjerry** [comment]
运行 python main.py 就出现这个

**Comment by Shu-Ji** [comment]
检查一下adb是否是环境变量里面
